sudo: true
language: haskell

git:
  depth: 5

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  - ghc: 8.6.5
  - ghc: 8.8.3
  
  - ghc: 8.8.3
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack-8.8.3.yaml"
  
  - ghc: 8.6.5
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"
  

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal v2-update
      cabal v2-build --enable-tests --enable-benchmarks
    else
      curl -sSL https://get.haskellstack.org/ | sh
      stack --version
      stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal v2-test --enable-tests
    else
      stack test --system-ghc
    fi

notifications:
  email: false
