cabal-version: 3.0
name: laop
version: 0.2.0.0
synopsis: Matrix programming library
description:
  Matrix programming library that uses a type-safe inductive definition
  inspired by the Linear Algebra of Programming

homepage: https://github.com/bolt12/laop
bug-reports: https://github.com/bolt12/laop/issues
license: MIT
license-file: LICENSE
author: Armando Santos
maintainer: Armando Santos <armandoifsantos@gmail.com>
copyright: 2023 Armando Santos
category: Data
build-type: Simple
extra-doc-files:
  CHANGELOG.md
  README.md

tested-with: ghc ==9.10.3 || ==9.12.3

source-repository head
  type: git
  location: https://github.com/bolt12/laop.git

common common-options
  build-depends: base >=4.20 && <5
  ghc-options:
    -Wall
    -Wno-unticked-promoted-constructors
    -Wcompat
    -Wincomplete-uni-patterns
    -Wincomplete-record-updates
    -Wpartial-fields
    -Widentities
    -Wredundant-constraints
    -Wunused-packages
    -fhide-source-paths
    -Wmissing-export-lists

  default-language: GHC2024

common executable-options
  ghc-options:
    -threaded
    -rtsopts

library
  import: common-options
  hs-source-dirs: src
  build-depends:
    array >=0.5.7 && <0.6,
    deepseq >=1.5 && <1.6,
    parallel >=3.2 && <3.4,

  exposed-modules:
    LAoP.Category
    LAoP.Dist
    LAoP.Dist.Internal
    LAoP.Index
    LAoP.Index.Internal
    LAoP.Matrix.Indexed
    LAoP.Matrix.Internal
    LAoP.Matrix.Nat
    LAoP.Matrix.Type
    LAoP.Relation
    LAoP.Relation.Internal
    LAoP.Utils
    LAoP.Utils.Internal

  other-modules:
    LAoP.Matrix.Internal.Biproduct
    LAoP.Matrix.Internal.Boolean
    LAoP.Matrix.Internal.Composition
    LAoP.Matrix.Internal.Construction
    LAoP.Matrix.Internal.Dim
    LAoP.Matrix.Internal.Elementwise
    LAoP.Matrix.Internal.Kronecker
    LAoP.Matrix.Internal.Relational
    LAoP.Matrix.Internal.Representation

test-suite laop-test
  import: common-options, executable-options
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  -- Every core, so that the parallel tests run their sparks.
  ghc-options: -with-rtsopts=-N
  other-modules:
    Examples.Quantum
    Examples.Readme
    Examples.Spreadsheets
    Test.Dist.Properties
    Test.Generators
    Test.Index.Properties
    Test.Matrix.Composition
    Test.Matrix.Properties
    Test.Matrix.Reference
    Test.Nat.Properties
    Test.Relation.Properties

  main-is: Spec.hs
  build-depends:
    QuickCheck >=2.15 && <2.19,
    laop,
    matrix >=0.3.6 && <0.4,
    tasty >=1.5 && <1.6,
    tasty-hunit >=0.10 && <0.11,
    tasty-quickcheck >=0.11 && <0.12,

benchmark laop-benchmark
  import: common-options, executable-options
  type: exitcode-stdio-1.0
  hs-source-dirs: benchmark
  main-is: Main.hs
  build-depends:
    QuickCheck,
    criterion,
    deepseq,
    laop,
