name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cabal: ["3.0"]
        ghc:
          - "ghc927"
          - "ghc96"
          - "ghc910"

    steps:
    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v20
      name: Install Nix

    - name: Build
      run: |
        nix build .#${{ matrix.ghc }}-laop


    - name: Test
      run: |
        nix develop .#${{ matrix.ghc }}-laop -c cabal v2-test --enable-tests
