name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cabal: ["3.0"]
        ghc:
          - "ghc8107"
          - "ghc92"

    steps:
    - uses: actions/checkout@v2.3.1
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: cachix/install-nix-action@v20
      name: Install Nix

    - name: Build
      run: |
        nix-build --attr exe --argstr compiler ${{ matrix.ghc }}

    - name: Test
      run: |
        nix-shell --argstr compiler ${{ matrix.ghc }} --run 'cabal v2-test --enable-tests'
