name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        cabal: ["3.0"]
        ghc:
          - "ghc865"
          - "ghc883"

    steps:
    - uses: actions/checkout@v2.3.1
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    #- uses: actions/setup-haskell@v1
    #  name: Setup Haskell
    #  with:
    #    ghc-version: ${{ matrix.ghc }}
    #    cabal-version: ${{ matrix.cabal }}

    #- uses: actions/cache@v1
    #  name: Cache ~/.cabal/store
    #  with:
    #    path: ~/.cabal/store
    #    key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - uses: cachix/install-nix-action@v10
      name: Install Nix

    - uses: cachix/cachix-action@v6
      if: matrix.ghc == 'ghc883' # Push to cachix only the most up to date GHC version
      with:
        name: bolt12-laop
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build
      run: |
        nix-build --attr exe --argstr compiler ${{ matrix.ghc }}

    - name: Test
      run: |
        nix-shell --argstr compiler ${{ matrix.ghc }} --run 'cabal v2-test --enable-tests'

